### ISSUE TITLE
Update CEN config for MultiQC v1.25.2

### ISSUE THREAD

**Issue by Yu-jinKim** [eastgenomics/eggd_MultiQC_configs#21]
Need to update the `pconfig` section to make it work: https://platform.dnanexus.com/panx/projects/Gx2ybJ84VBXQkyYbkpZKp0bP/monitor/job/Gx6vQ2j4VBXy4xVXbV2qY1Xx
```yaml
# Add code to include data from custom QC data files
custom_data:
    vcf_qc_files:
        file_format: 'tsv'
        section_name: 'Het-hom analysis'
        description: 'This plot comes from vcf_qc files'
        plot_type: 'table'
        pconfig:
            id: 'het-hom_table'
            title: 'Het-hom'
        headers:
            mean het ratio:
                title: "Mean Heterozigoty Ratio"
                format:  '{:,.2f}'
            mean homo ratio:
                title: "Mean Homozigoty Ratio"
                format:  '{:,.2f}'
            het:homo ratio:
                title: "Het:Hom ratio"
                format:  '{:,.2f}'
            X homo:het ratio:
                title: "X Hom:Het ratio"
                format:  '{:,.2f}'
```
